#ifndef GUARD_CONSTANTS_VARIANTS_H
#define GUARD_CONSTANTS_VARIANTS_H

#define VARIANT_DEFAULT 0
#define VARIANT_RANDOM  8

#define VARIANT_PARTS_ANY   0

#define VARIANT_BULBASAUR_ORIGINAL  0
#define VARIANT_BULBASAUR_RED       1
#define VARIANT_BULBASAUR_GREEN     2
#define VARIANT_BULBASAUR_BLUE      3
#define VARIANT_BULBASAUR_PINK      4
#define NUM_VARIANT_BULBASAUR       5

#define VARIANT_PARTS_BULBASAUR_SKIN    0
#define VARIANT_PARTS_BULBASAUR_BULB    1
#define VARIANT_PARTS_BULBASAUR_MOUTH   2

#define VARIANT_CHARMANDER_ORIGINAL 0
#define VARIANT_CHARMANDER_RED      1
#define VARIANT_CHARMANDER_GREEN    2
#define VARIANT_CHARMANDER_BLUE     3
#define VARIANT_CHARMANDER_WHITE    4
#define NUM_VARIANT_CHARMANDER      5

#define VARIANT_PARTS_CHARMANDER_SKIN   0
#define VARIANT_PARTS_CHARMANDER_FLAME  1
#define VARIANT_PARTS_CHARMANDER_EYES   2

#define VARIANT_SQUIRTLE_ORIGINAL   0
#define VARIANT_SQUIRTLE_RED        1
#define VARIANT_SQUIRTLE_GREEN      2
#define VARIANT_SQUIRTLE_BLUE       3
#define VARIANT_SQUIRTLE_PINK       4
#define NUM_VARIANT_SQUIRTLE        5

#define VARIANT_PARTS_SQUIRTLE_SKIN     0
#define VARIANT_PARTS_SQUIRTLE_SHELL    1
#define VARIANT_PARTS_SQUIRTLE_MOUTH    2

#endif // GUARD_CONSTANTS_VARIANTS_H
