#ifndef GUARD_CONSTANTS_VARIANTS_H
#define GUARD_CONSTANTS_VARIANTS_H

#define VARIANT_DEFAULT 0
#define VARIANT_RANDOM 8

#define VARIANT_BULBASAUR_ORIGINAL  0
#define VARIANT_BULBASAUR_RED       1
#define VARIANT_BULBASAUR_GREEN     2
#define VARIANT_BULBASAUR_BLUE      3
#define VARIANT_BULBASAUR_PINK      4
#define NUM_VARIANT_BULBASAUR       5

#define VARIANT_CHARMANDER_ORIGINAL 0
#define VARIANT_CHARMANDER_RED      1
#define VARIANT_CHARMANDER_GREEN    2
#define VARIANT_CHARMANDER_BLUE     3
#define VARIANT_CHARMANDER_WHITE    4
#define NUM_VARIANT_CHARMANDER      5

#define VARIANT_SQUIRTLE_ORIGINAL   0
#define VARIANT_SQUIRTLE_RED        1
#define VARIANT_SQUIRTLE_GREEN      2
#define VARIANT_SQUIRTLE_BLUE       3
#define VARIANT_SQUIRTLE_PINK       4
#define NUM_VARIANT_SQUIRTLE        5

#endif // GUARD_CONSTANTS_VARIANTS_H
