PalletTown_PlayersHouse_2F_Text_PlayedWithSwitchScarlet::
    .string "{PLAYER} played POKéMON SCARLET\n"
    .string "on the Nintendo Switch!\p"
    .string "KORAIDON: Agias!$"

PalletTown_PlayersHouse_2F_Text_PlayedWithSwitchViolet::
    .string "{PLAYER} played POKéMON VIOLET\n"
    .string "on the Nintendo Switch!\p"
    .string "MIRAIDON: Agias!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice…\p"
    .string "Check BULBAPEDIA for help!$"
